version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_consulta
    restart: always
    environment:
      MYSQL_DATABASE: consulta_medica
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: