spring.application.name=ConsultaMedica

server.port=${PORT:8080}

spring.datasource.url=jdbc:${DATABASE_URL:mysql://localhost:3306/consulta_medica?serverTimezone=UTC}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver [cite: 54]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true